# Generated by Django 4.1.3 on 2022-11-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myprojects_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myprojects_title', models.CharField(max_length=50)),
                ('myprojects_type', models.CharField(max_length=50)),
                ('myprojects_lang', models.CharField(max_length=50)),
                ('myprojects_desc', models.TextField()),
            ],
        ),
    ]
