# Generated by Django 4.1.3 on 2022-11-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects_model',
            name='myprojects_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
