# Generated by Django 4.1.3 on 2022-11-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_course_title', models.CharField(max_length=100)),
                ('education_course_collge', models.CharField(max_length=100)),
                ('education_course_year', models.CharField(max_length=10)),
                ('education_course_desc', models.TextField()),
            ],
        ),
    ]
