# Generated by Django 4.1.3 on 2022-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education_model',
            old_name='education_course_collge',
            new_name='education_course_college',
        ),
    ]
