# Generated by Django 4.1.3 on 2022-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myportfolio_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myportfolio_img', models.ImageField(default=None, max_length=500, null=True, upload_to='myportfolio_img')),
            ],
        ),
    ]
