# Generated by Django 4.1.3 on 2022-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio_model',
            name='myportfolio_img_alt_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
