# Generated by Django 4.1.3 on 2022-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_myportfolio_model_myportfolio_img_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolio_model',
            name='myportfolio_img_alt_text',
            field=models.CharField(default='portfolio', max_length=200, null=True),
        ),
    ]
