# Generated by Django 4.1.3 on 2022-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_alter_myportfolio_model_myportfolio_img_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio_model',
            name='myportfolio_number',
            field=models.IntegerField(null=True),
        ),
    ]
