# Generated by Django 4.1.3 on 2022-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_myportfolio_model_myportfolio_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio_model',
            name='myportfolio_img_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
