# Generated by Django 4.1.3 on 2022-11-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_myportfolio_model_myportfolio_img_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myportfolio_model',
            name='myportfolio_number',
        ),
    ]
