# Generated by Django 4.1.3 on 2022-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation_text', models.CharField(max_length=50)),
                ('my_name', models.CharField(max_length=50)),
                ('my_image', models.ImageField(default=None, max_length=500, null=True, upload_to='main_image')),
                ('my_image_alt_text', models.CharField(max_length=200)),
            ],
        ),
    ]
