# Generated by Django 4.1.3 on 2022-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_model',
            name='my_image_alt_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='header_model',
            name='my_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='header_model',
            name='salutation_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
