# Generated by Django 4.1.3 on 2022-11-13 13:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_model',
            name='about_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
