# Generated by Django 4.1.3 on 2022-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_model_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_model',
            name='about_image_alt_text',
            field=models.CharField(default='Abhishek Gupta', max_length=200),
        ),
    ]
