# Generated by Django 4.1.3 on 2022-11-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_model',
            name='skill_progress_bar_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
