# Generated by Django 4.1.3 on 2022-11-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_model_skill_margin_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_model',
            name='skill_margin_bottom',
        ),
    ]
